#!/bin/sh

music_dir="/home/harrison/Music"
previewdir="/home/harrison/.ncmpcpp/previews"
filename="$(mpc --format "$music_dir"/%file% current)"
previewname="$previewdir/$(mpc --format %album% current | base64).png"

[ -e "$previewname" ] || ffmpeg -y -i "$filename" -an -vf scale=128:128 "$previewname" > /dev/null 2>&1

dunstify -a "songinfo" -r 9990 "$(mpc --format '\n%artist% - %title%' current)" -i "$previewname" -t 100000

